

x-airflow-common: &airflow-common
  image: apache/airflow:2.8.0
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'supersecretkey123'
    MONGO_URI: mongodb://mongo:27017/
    POSTGRES_CONN: postgresql://pipeline:pipeline@postgres:5432/ecommerce
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./spark:/opt/spark_jobs
    - ./ingestion:/opt/ingestion
    - ./data:/opt/data
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8085:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin
               --firstname Admin --lastname User --role Admin
               --email admin@example.com"

  spark:
    image: apache/spark:3.5.0
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark:/opt/spark_jobs
      - ./data:/opt/data
    ports:
      - "7077:7077"
      - "8081:8080"
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  mongo_data: